name: zorya_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  google_fonts: ^6.1.0
  segmented_button_slide: ^1.0.4
  slide_switcher: ^1.1.2
  animated_notch_bottom_bar: ^1.0.0
  flutter_svg: ^2.0.9
  bottom_bar: ^2.0.3
  persistent_bottom_nav_bar: ^5.0.2
  bottom_navy_bar: ^6.0.0
  magic_text: ^0.0.3
  responsive_sizer: ^3.2.0
  linkable: ^3.0.2
  url_launcher: ^6.1.14
  scroll_navigation: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/registration/regscreen.jpg
    - assets/registration/regscreen1.png
    - assets/logos/white_logo.png
    - assets/logos/white_logo_long.jpeg
    - assets/logos/osbb_white_logo.jpg
    - assets/logos/osbb_white_logo.png
    - assets/logos/brown_logo.jpeg
    - assets/home/home_back.jpg
    - assets/home/q1.png
    - assets/home/q1-s1.png
    - assets/home/q1-s2.png
    - assets/home/s2-f0.png
    - assets/home/s1-f0.png
    - assets/home/s1-f1.png
    - assets/home/s1-f2.png
    - assets/home/s1-f3.png
    - assets/home/s1-f4.png
    - assets/home/s1-f5.png
    - assets/home/s1-f6.png
    - assets/home/s1-f7.png
    - assets/home/s1-f8.png
    - assets/home/s1-f9.png
    - assets/home/s2-f1.png
    - assets/home/s2-f2.png
    - assets/home/s2-f3.png
    - assets/home/s2-f4.png
    - assets/home/s2-f5.png
    - assets/home/s2-f6.png
    - assets/home/s2-f7.png
    - assets/home/s2-f8.png
    - assets/home/s2-f9.png
    - assets/pick/orig_pick.jpg