name: zorya_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  google_fonts: ^6.1.0
  segmented_button_slide: ^1.0.4
  slide_switcher: ^1.1.2
  animated_notch_bottom_bar: ^1.0.0
  flutter_svg: ^2.0.9
  bottom_bar: ^2.0.3
  persistent_bottom_nav_bar: ^5.0.2
  bottom_navy_bar: ^6.0.0
  magic_text: ^0.0.3
  responsive_sizer: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/registration/regscreen.jpg
    - assets/registration/regscreen1.png
    - assets/logos/white_logo.png
    - assets/logos/white_logo_long.jpeg
    - assets/logos/osbb_white_logo.jpg
    - assets/logos/osbb_white_logo.png
    - assets/logos/brown_logo.jpeg
    - assets/home/home_back.jpg
    - assets/pick/orig_pick.jpg