name: flutter_application_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  google_fonts: ^6.1.0
  segmented_button_slide: ^1.0.4
  slide_switcher: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/registration/regscreen.jpg
    - assets/white_logo.png
    - assets/home/home_back.jpg